server:
  port: 9192

spring:
  datasource:
    username: root
    password: my-secret-pw
    url: jdbc:mysql://localhost:3306/StudentDatabase
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format-sql: true

